### ISSUE TITLE
matplotlib.use(‘Agg’) 位置错误导致backend设置失败

### ISSUE THREAD

**Issue by wintericie** [QuantumLiu/wechat_callback#3]
刚刚安装了wechat_callback插件，然后在跑程序的时候报了以下warning：
`/usr/local/lib/python3.5/dist-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.`

然后跑了两个epoch，输出第四张图的时候，callback会卡住，并输出以下信息：
`Tcl_AsyncDelete: cannot find async handler`
接着程序就core dump了。

修改wechat_utils.py的import部分，把 import marplotlib.pyplot as plt 放在 marplotlib.use('Agg') 后，程序可以正常运行，第一段matplotlib的warning也未出现过。

麻烦作者改一下这里吧。

**Comment by QuantumLiu** [comment]
谢谢反馈，我前几天在本地改了，忘了更新。
